# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Quinncheong.com
subtitle: "Home of Quinn's explorations"
name: "Quinn Cheong"
email: quinncheong@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My personal site where I share about the things I'm learning, my explorations, and experiences that I've had. I hope that we'll have some great conversations.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://quinncheong.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/images/Q_logo_small.png"
# No twitter for now as I dont use twitter alot
# twitter_username: quinn_cheong
github_username:  quinncheong
linkedin_username:  quinncheong
instagram_username: quinnizso
minimal_mistakes_skin: dark # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
search: true
breadcrumbs: true  # disabled by default

copyright: Quinn

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Google Analytics
# google_analytics: G-4E627E9911
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-4E627E9911"
    anonymize_ip: false # default

author:
  name   : "Quinn Cheong"
  avatar : "/assets/images/Quinn_pfp.jpg"
  bio    : "Place where I document my failures and successes for personal analysis."
  location : "Singapore, Singapore"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://quinncheong.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/quinncheong"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/quinncheong"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/quinnizso"

# For SEO
social:
  type: Person # Person or Organization (defaults to Person)
  name:  # If the user or organization name differs from the site's name
  links:
    - "https://www.facebook.com/Quinncheong"
    - "https://instagram.com/quinnizso"
    - "https://linkedin.com/in/quinncheong"
    - "https://github.com/quinncheong"

og_image: "/assets/images/logo.png"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/quinncheong"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/quinncheong"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/quinnizso"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
      comments:
        provider: "facebook"
        facebook:
          appid: # optional
          num_posts: 5 # 5 (default)
          colorscheme: dark # "light" (default), "dark"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Server Config options
incremental: false
livereload: true


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
